### PR TITLE
docs(woocommerce): how to add discounts on woo

### PR DESCRIPTION
**Pull request by noghartt**
resolve https://github.com/entria/woovi/issues/44942

### CODE REVIEW

**Review by daniloab — COMMENTED** [review]
prefer to add inside woocommerce folder

**Review by edumaciel10 — COMMENTED** [review]
Use github images are ok? Not decrease the quality?

**Comment by noghartt** [comment]
> Use github images are ok? Not decrease the quality?

Just what the CDN uses as optimization to the image inside their CDN domain. But in general, it's don't decrease a lot of quality.

Would be better if we have our images in a kind of CDN or anything else.

**Comment by edumaciel10** [comment]
> > Use github images are ok? Not decrease the quality?
> 
> Just what the CDN uses as optimization to the image inside their CDN domain. But in general, it's don't decrease a lot of quality.
> 
> Would be better if we have our images in a kind of CDN or anything else.

Ok

**Pull request merged**
